# Generated by Django 4.1.1 on 2022-09-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('picture_1', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('picture_2', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('picture_3', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Контент главной страницы',
                'verbose_name_plural': 'Контент главной страницы',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Посты',
                'verbose_name_plural': 'Посты',
                'ordering': ['-time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SocialNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=250)),
                ('facebook', models.CharField(max_length=250)),
                ('youtube', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Соцсети',
                'verbose_name_plural': 'Соцсети',
            },
        ),
    ]
