# Generated by Django 4.1.1 on 2022-09-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default=111, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
