# Generated by Django 4.1.1 on 2022-09-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutsite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsite',
            options={'verbose_name': 'Контент страницы <О блоге>', 'verbose_name_plural': 'Контент страницы <О блоге>'},
        ),
        migrations.AddField(
            model_name='aboutsite',
            name='facebook_link',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutsite',
            name='instagram_link',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutsite',
            name='linkedn_link',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutsite',
            name='my_mail',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='aboutsite',
            name='my_phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='aboutsite',
            name='youtube_link',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
