# Generated by Django 4.1.1 on 2022-09-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_aboutsite_options_aboutsite_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsite',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutsite',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutsite',
            name='linkedn_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutsite',
            name='my_mail',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='aboutsite',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
