# Generated by Django 4.1.1 on 2022-09-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='content_2part',
            field=models.TextField(null=True),
        ),
    ]
