# Generated by Django 4.1.1 on 2022-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_city_content_2part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=255)),
                ('card_1', models.CharField(max_length=16)),
                ('card_2', models.CharField(max_length=16)),
                ('card_3', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Спонсорство',
                'verbose_name_plural': 'Спонсорство',
            },
        ),
    ]
